### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Tager1** [owiecc/SAM-Z-scan#1]
Error using fseek
Invalid file identifier. Use fopen to generate a valid file identifier.

**Comment by owiecc** [comment]
Which `fseek` throws this error? Can you write how to reproduce the error?

**Comment by Tager1** [comment]
Thank you for rapid response. I attached a screenshot, in MATLAB 2017b.

**Comment by owiecc** [comment]
Sorry, I don't see any attachments here. Can you just copy the error message with the line number? What kind of input do you give to the script?
